# Generated by Django 4.1.7 on 2023-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(null=True, verbose_name="Дата рождения"),
        ),
    ]
