# Generated by Django 4.1.7 on 2023-03-25 16:20

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    user.validators.EmailDomainValidator(["mail.ru", "yandex.ru"])
                ],
                verbose_name="email",
            ),
        ),
    ]
